name: "CI"
on: [push, pull_request]

jobs:
  build:
    name: Nix Build (nixpkgs-${{ matrix.nixpkgs }}, enableCUDA=${{ matrix.cuda }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nixpkgs: ['unstable', '21.05']
        cuda: ['false', 'true']
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-${{ matrix.nixpkgs }}
      - run: nix-build --arg enableCUDA ${{ matrix.cuda }}
        env:
          NIXPKGS_ALLOW_UNFREE=1
